version: 2.1

orbs:
  python: circleci/python@0.3.0

jobs:
  build-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - python/test
      - run:
          command: |
            python3 setup.py sdist
          name: Create package
      - persist_to_workspace:
          root: .
          paths:
            - dist/*  
  deploy:
    executor: python/default
    description: |
      Publish the PyPI package
    steps:
      - run:
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = $PYPI_USERNAME" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
          name: Init .pypirc
      - run:
          command: |
            pip install --user setuptools wheel twine
          name: Install publish dependencies
      - attach_workspace:
          at: .
      - run:
          command: |
            twine upload --skip-existing dist/*
          name: Upload to pypi if new release version


workflows:
  build_test_and_deploy:
    jobs:
      - build-test
      - deploy:
          requires:
            - build-test
          filters:
            branches:
              only: master
